### DISCUSSION TITLE
How to specify gnat version with action setup-alire@v1

### DISCUSSION THREAD

**Discussion by pjljvandelaar** [alire-project/alire#1177] [Q&A]
On https://github.com/alire-project/setup-alire is written

```
To use the latest binary release of the Alire project, add this line to your workflow steps:
    - uses: alire-project/setup-alire@v1
 ```

However, I have problems with the latest binary release on windows.
Already installing this version breaks my earlier perfectly working code.

I tried adding
```
[depends-on.'case(os)'.windows]
gnat = "<=11.2.4"
```
and
```
[depends-on.'case(os)'.windows]
gnat_native = "<=11.2.4"
```
to my alire.toml file, but still gnat 12.1.2 (the latest) is installed.
Of course, GNAT_Native 11.2.4 is used to build.

I also read on https://github.com/alire-project/setup-alire
```
To use a development version compiled from sources (if you known what you are doing), add instead these two steps to you workflow:

    - uses: ada-actions/toolchain@ce2020
    - uses: alire-project/setup-alire@v1
      with:
        branch: "master" # or the branch you want to use
```

I don't know how the coding of the toolchain works: 
 what is ce2020 in relation to gnat?
 Is there also a ce2021, ce2022?

And, I don't know what I am doing, so my question:
```
What instructions are needed to set-up alire with at most gnat 11.2.4?
```

Greetings,
  Pierre
