### DISCUSSION TITLE
Easy access to TOML metadata from source code?

### DISCUSSION THREAD

**Discussion by ulahello** [alire-project/alire#1927] [Q&A] [answered]
Hi, I'm currently to access the crate description from the source code; it would be nice to do this without duplicating the value.

The closest I can think of is putting something like this in `configuration.variables`, but this still duplicates information:
```toml
description = "whimsical description"

# ...

[configuration.variables]
# TODO: some way to reference the actual description?
Crate_Description = { type = "String", default = "whimsical description" }
```

Is there currently a nice way to accomplish this? Or is this worth a PR?
