### DISCUSSION TITLE
What oses are available in alire workflow?

### DISCUSSION THREAD

**Discussion by pjljvandelaar** [alire-project/alire#1951] [Q&A]
In my `.github\workflows` directory I have files containing
```
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
```

I am wondering what oses can I chose?

Looking at https://alire-crate-ci.ada.dev/crates/dependency_graph_extractor.html
I guess I could add macos, debian, centos, and fedora.
But is that true? And are that all possible oses?
