### ISSUE TITLE
Tackle availability with special dependencies

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#110]
Right now we have two distinct conditional expressions:
- `depends-on`, that resolve to a plaform-specific list of dependencies
- `available`, that resolve to a boolean

The `available` field is inspired from `opam`. Another way of doing the same would be to create platform-specific dependencies on which to depend (this is done by other PMs).

Example (current):
```toml
[depends-on]
libfoo = "1.0"
['available.case(os)']
linux = true
'...' = false
```

Example (alternative):
```toml
[depends-on]
libfoo="1.0"
['depends-on.case(os)']
linux = { 'alr.platform.os.linux' = "any" }
'...' = { 'alr.unavailable' = "any" }
```

Where `alr.platform.os.linux` ~(optional: #108)~ or something equivalent would be a special release generated by alr only when on linux. Syntax could be improved somehow.

- Pros: we get rid of one class of expressions, having only one class to maintain.
- Cons: it seems like an indirect way of expressing a purpose. Something unforeseen might arise down the road that required the `available` boolean cases anyway. Some dependencies could be awkward, since they aren't really versioned (architecture for example).

I recognize I was and I am torn about this. On the one hand, consolidating the feature seems appealing. We could populate the child alr.* hierarchy as needs arose. I don't really remember anymore why in the end I went the opam way, which in turn is unsettling, because I saw some clear advantage. It's true that at the time the platform specific aspects of alr where more in flux.

Furthermore, I see that currently opam has something similar (although values need not be semantic versions, which may be the main deterrent here): https://opam.ocaml.org/blog/opam-extended-dependencies/

The available field in opam is explained here: https://opam.ocaml.org/doc/Manual.html#opamfield-available

I see one reason can be that that field is faster to evaluate that doing fully-fledged dependency resolution. Still, from those two links, I see a duplication of functionality in opam. I was not able to locate something similar in rust.

Since this is a major change, I guess the more eyes the better, @pmderodat, @Fabien-Chouteau 

Also related to #109
