### ISSUE TITLE
using pins with a path on arm64 causes infinite loop

### ISSUE THREAD

**Issue by dalybrown** [alire-project/alire#1498]
I'm not sure if this has been mentioned in other issues. I'm using an `arm64` linux container and I can never get pins to work properly.

As a basic example, I want to with a dependency in another folder.

```toml
[[depends-on]]
dependency = "*"

[[pins]]
dependency = { path = "path/to/dependency" }
```

This will cause alire to spin out of control. On a related note, I can't use the command `alr with dependency --use /path/to/dependency` to set this up because it will print an error:

```
error: Loading release from manifest: /workspaces/reproducer/alire/tmp/alr-kpcu.tmp:
error:    Failed to load /workspaces/reproducer/alire/tmp/alr-kpcu.tmp:
error:    invalid path name ""
```

I'm using this version of alire: `alr 1.2.1`.

I'm using this architecture: `aarch64 GNU/Linux`.
