### ISSUE TITLE
Manifest format: multiple commands in a single action definition

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#538]
Right now the actions are defined like so:
```toml
[[actions]]
type = "post-build"
command = ["echo", "test_post_build"]
```
If someone wants two `post-build` actions, the manifest will be:
```toml
[[actions]]
type = "post-build"
command = ["echo", "test_post_build_1"]
[[actions]]
type = "post-build"
command = ["echo", "test_post_build_2"]
```

We could support a shorter version by accepting multiple commands in a single action definition:
```toml
[[actions]]
type = "post-build"
command = [["echo", "test_post_build_1"], ["echo", "test_post_build_2"]]
```
