### ISSUE TITLE
Alire builds crate that is not available on current OS

### ISSUE THREAD

**Issue by onox** [alire-project/alire#769]
My orka_egl crate's alire.toml file contains:

```toml
[available.'case(os)']
linux = true
'...' = false
```

Yet, it happily runs `alr build` on windows-latest (with ce2021 compiler) during GitHub Actions. It compiles with no errors, but then fails with `ld.exe: cannot find -lEGL` (which is why the crate is not available on windows).

Shouldn't alr just do nothing if `available.'case(os)'` says it's not available?
