### ISSUE TITLE
Adding trusted sites

### ISSUE THREAD

**Issue by Patschkowski** [alire-project/alire#814]
Dear all,

we are very close to fully adopting Alire for our projects. External dependencies are pulled from the Alire index.

What we still want to do is also split our internal dependencies into different repos. Currently, all our code lives in one repo.

Due to IP we can not host the repos externally on the trusted sites that are currently allowed by Alire. Is there a way we can add our in-house Git server to the list of trusted sites?

Kind regards,
Felix

**Comment by Fabien-Chouteau** [comment]
Hello @Patschkowski,

My understanding is that this trusted site check is only made in the `alr publish` command. You don't have to use this command to publish a crate in your local index. Just renaming the `alire.toml` into `<crate_name>-<crate_version>.toml` and adding
```toml
[origin]
commit = "ac734659560ffa98346c4ddc97d8966471d70374"
url = "git+https://github.com/alire-project/clic.git"
```
 should be enough.

What we can try to do in future versions is to read a list of trusted sites from the user configuration files.
