### ISSUE TITLE
Side effect of gprbuild checkout

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#864]
Hello!
I have this GitHub Action workflow:
```
on:
  push:
    branches:
      - master
name: Build binaries
jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Get gprbuild
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gprbuild
          path: gprbuild
      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v1
        with:
          toolchain: gnat_native^11 gprbuild^21 --disable-assistant
          toolchain_dir: ./cached_gnat
```

The `alire-project/setup-alire@v1` step fails on windows (works on macos/linux). Error is:

```
Note: gprbuild=21.0.1 installed successfully.
Installed alr version and GNAT toolchain:
D:\a\test\test\alire_install\bin\alr.exe -n version
Alr version: 1.1.0
Alire Library version: 1.1.0
alr status is (outside) (0 releases indexed) (loaded in 0.046s)
config folder is C:\Users\runneradmin\.config\alire
source folder is C:\Users\runneradmin\.config\alire\alire
interaction flags are: force:FALSE not-interactive:TRUE
alr root is empty
alr root detection has settled on path: D:\a\test\test
alr is finding 0 GPR project files
alr session state is [OUTSIDE]
alr compiled on [2021-09-16 15:28:36] with GNAT version [Community 2021 (20210519-103)]
platform fingerprint: Windows Bits_64 Msys2
platform properties: MSYS2 WINDOWS NATIVE USER BITS_64
community index required branch: stable-1.1
D:\a\test\test\alire_install\bin\alr.exe -n toolchain
ERROR: Command ["gprbuild", "--version"] exited with code-1 and output:
Error: The process 'D:\a\test\test\alire_install\bin\alr.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\alire-project\setup-alire\v1\node_modules\@actions\exec\lib\toolrunner.js:592:25)
    at ExecState.CheckComplete (D:\a\_actions\alire-project\setup-alire\v1\node_modules\@actions\exec\lib\toolrunner.js:575:18)
    at ChildProcess.<anonymous> (D:\a\_actions\alire-project\setup-alire\v1\node_modules\@actions\exec\lib\toolrunner.js:469:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: The process 'D:\a\test\test\alire_install\bin\alr.exe' failed with exit code 1
```

If I drop gprbuild checkout step, then it works fine.
